// Generated by scripts/prepare-sfx.py. Timings use decoded 48 kHz PCM.
export const sounds = [
  {
    "id": "click-soft",
    "name": "轻触",
    "src": "assets/sfx/click-soft.wav",
    "duration": 0.164479,
    "description": "安静的界面点按、选择与标签切换",
    "defaultGain": 0.36,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "click-soft: 安静的界面点按、选择与标签切换",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/click-soft.mp3",
      "sourceSha256": "075e17bdac5c13662a1c9530050e0046f81d4138e00eb3bf30427a7b4404103d",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "click",
    "name": "确认点按",
    "src": "assets/sfx/click.wav",
    "duration": 0.164479,
    "description": "清晰的按钮点击、开关落位与操作确认",
    "defaultGain": 0.42,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "click: 清晰的按钮点击、开关落位与操作确认",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/click.mp3",
      "sourceSha256": "075e17bdac5c13662a1c9530050e0046f81d4138e00eb3bf30427a7b4404103d",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "key-press",
    "name": "单键",
    "src": "assets/sfx/key-press.wav",
    "duration": 0.097625,
    "description": "命令输入、键盘快捷键与逐字提示",
    "defaultGain": 0.34,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "key-press: 命令输入、键盘快捷键与逐字提示",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/key-press.mp3",
      "sourceSha256": "bcc892df0898bf466162f14233c3e92a8c1ea351f6affd8a3a7e56c9a760bb72",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "typing",
    "name": "键入节奏",
    "src": "assets/sfx/typing.wav",
    "duration": 1.078667,
    "description": "短促连续输入，适合终端与代码打字",
    "defaultGain": 0.25,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "typing: 短促连续输入，适合终端与代码打字",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/typing.mp3",
      "sourceSha256": "944160652faeb7b32acc9341ede4d735a5c9a4ce3fe8509ef7eab91efb430487",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "pop",
    "name": "轻弹",
    "src": "assets/sfx/pop.wav",
    "duration": 0.296542,
    "description": "小卡片、标签、节点与角标出现",
    "defaultGain": 0.36,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "pop: 小卡片、标签、节点与角标出现",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/pop.mp3",
      "sourceSha256": "19ab7193f626ff57fdeef60b45543bac416fcbcec803cfb417abe4b271c1b352",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "ping",
    "name": "数据提示",
    "src": "assets/sfx/ping.wav",
    "duration": 0.638729,
    "description": "数值到位、关键数据与注释点亮",
    "defaultGain": 0.3,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "ping: 数值到位、关键数据与注释点亮",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/ping.mp3",
      "sourceSha256": "c54d088fa2709e6b3c9ce87594a9187d0d5338d3a8c683271f9c4353a8ee8c91",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "notification",
    "name": "消息到达",
    "src": "assets/sfx/notification.wav",
    "duration": 1.389792,
    "description": "消息气泡、通知与工具结果出现",
    "defaultGain": 0.28,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "notification: 消息气泡、通知与工具结果出现",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/notification.mp3",
      "sourceSha256": "b1559967dedb7994a82371f10cec9f7f3992e6b147b4cd88d62112bcdc3f9ba3",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "chime",
    "name": "完成和弦",
    "src": "assets/sfx/chime.wav",
    "duration": 1.75,
    "description": "成功、步骤完成与流程收束",
    "defaultGain": 0.28,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "chime: 成功、步骤完成与流程收束",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/chime.mp3",
      "sourceSha256": "74823b1b27703c56e0652db838f503c150ce9c2442d47d27430af3d5121d6d12",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "whoosh-short",
    "name": "短滑动",
    "src": "assets/sfx/whoosh-short.wav",
    "duration": 0.335979,
    "description": "面板轻移、抽屉展开与快速切换",
    "defaultGain": 0.3,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "whoosh-short: 面板轻移、抽屉展开与快速切换",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/whoosh-short.mp3",
      "sourceSha256": "c2efd9d902a59bf9ec5019035d7deadd17762136896b6e3cb6dd99ea50997a30",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "whoosh",
    "name": "柔和推移",
    "src": "assets/sfx/whoosh.wav",
    "duration": 0.335979,
    "description": "较大区域切换、镜头聚焦与信息揭示",
    "defaultGain": 0.28,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "whoosh: 较大区域切换、镜头聚焦与信息揭示",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/whoosh.mp3",
      "sourceSha256": "c2efd9d902a59bf9ec5019035d7deadd17762136896b6e3cb6dd99ea50997a30",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "sparkle",
    "name": "轻亮点",
    "src": "assets/sfx/sparkle.wav",
    "duration": 1.35,
    "description": "重点词、标记高光与小范围强调",
    "defaultGain": 0.23,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "sparkle: 重点词、标记高光与小范围强调",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/sparkle.mp3",
      "sourceSha256": "a66b2829a307bcb5b1f6551d7cdc72fe45bbe9a91abfb994d28db8d5e4e42ea8",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "error",
    "name": "温和错误提示",
    "src": "assets/sfx/error.wav",
    "duration": 0.31925,
    "description": "校验失败或撤销提醒，避免警报式高音量",
    "defaultGain": 0.25,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "error: 校验失败或撤销提醒，避免警报式高音量",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/error.mp3",
      "sourceSha256": "b4882e3941ca496b5038e7c7d64318419da9f69d3da9540a1c693adc639cf121",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  },
  {
    "id": "riser",
    "name": "柔和渐进",
    "src": "assets/sfx/riser.wav",
    "duration": 1.55,
    "description": "数据递增与进度完成前的轻量上升提示",
    "defaultGain": 0.23,
    "license": "Pixabay Content License",
    "provenance": {
      "provider": "media-use.bundled-sfx",
      "prompt": "riser: 数据递增与进度完成前的轻量上升提示",
      "claimedOrigin": "Pixabay",
      "sourceFile": ".media/sfx-source/riser.mp3",
      "sourceSha256": "d2f29d49f27dee7d3b25af22ffe5bebc39390cc5d5fb3b3e1c433499c77f3d1d",
      "license": "Pixabay Content License",
      "licenseUrl": "https://pixabay.com/service/license-summary/",
      "individualAuthorAndItemUrl": "not supplied by bundle",
      "recordingOrSynthesis": "not established; not claimed as original recording"
    }
  }
];
export const soundById = Object.fromEntries(sounds.map(sound => [sound.id, sound]));
