import {components} from '../../registry.mjs';
import {helpers,esc} from '../../shared.mjs';
import {normalizeMediaProps,rewriteRenderedMediaMarkup} from '../../content-runtime.mjs';
import {groups,names,variants,examples} from './parts.mjs';
const assetBase=new URL('../../',import.meta.url).href;
const atoms=components.filter(c=>c.category==='动画风 · 基础组件');
const order=groups.flatMap(g=>g.ids);
atoms.sort((a,b)=>order.indexOf(a.id.replace('ani-atom-',''))-order.indexOf(b.id.replace('ani-atom-','')));
const $=id=>document.getElementById(id);
let current=null,combined=false,activeGroup='全部';
function renderCombination(config){
 if(!Array.isArray(config)||!config.length||config.length>20)throw Error('组合需要 1–20 个部件。');
 const groups=config.map((item,i)=>{const c=atoms.find(x=>x.id===item.component);if(!c)throw Error('组合中含未知部件：'+item.component);const div=document.createElement('div');div.innerHTML=c.render({...c.defaults,...item.props},helpers('combo-'+i));const svg=div.querySelector('svg');if(!svg)throw Error('组件缺少 SVG');const p={x:0,y:0,scale:1,...item.placement};if(![p.x,p.y,p.scale].every(Number.isFinite)||p.scale<=0||p.scale>5)throw Error('placement 使用数字 x、y 和 0–5 的 scale');return `<g data-instance="${i}" transform="translate(${p.x} ${p.y}) scale(${p.scale})">${svg.innerHTML}</g>`;});
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720" width="1280" height="720" font-family="Microsoft YaHei,Segoe UI,sans-serif" font-weight="750" fill="#102b62">${groups.join('')}</svg>`;
}
function apply(){try{const props=normalizeMediaProps(JSON.parse($('props').value));const html=combined?renderCombination(props):current.render({...current.defaults,...props},helpers('atom-live'));$('stage').innerHTML=rewriteRenderedMediaMarkup(html,assetBase);$('error').textContent='';}catch(error){$('error').textContent='请检查配置：'+error.message;}}
function showVariants(c){$('variants').replaceChildren();for(const [label,patch] of [['默认',{}],...(variants[c.id.replace('ani-atom-','')]||[])]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',String(label==='默认'));b.onclick=()=>{$('props').value=JSON.stringify({...c.defaults,...patch},null,2);apply();$('variants').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));};$('variants').append(b);}}
function select(c){current=c;combined=false;$('name').textContent=c.name;$('description').textContent=c.description;$('props').value=JSON.stringify(c.defaults,null,2);$('editor-title').textContent='替换内容';$('catalog-edit').hidden=false;$('catalog-edit').href='../../catalog.html?component='+encodeURIComponent(c.id);document.querySelectorAll('.part').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===c.id)));showVariants(c);const url=new URL(location.href);url.searchParams.set('component',c.id);history.replaceState(null,'',url);apply();}
for(const c of atoms){const short=c.id.replace('ani-atom-',''),group=groups.find(g=>g.ids.includes(short))?.name||'其他';const b=document.createElement('button');b.className='part';b.dataset.id=c.id;b.dataset.group=group;b.setAttribute('aria-pressed','false');b.innerHTML=`<div class="thumb">${c.render(c.defaults,helpers('thumb-'+c.id))}</div><span>${esc(names[short]||c.name)}</span><small>${esc(group)}</small>`;b.onclick=()=>select(c);$('grid').append(b);const svg=b.querySelector('svg');requestAnimationFrame(()=>{try{const r=svg.getBBox(),m=26;svg.setAttribute('viewBox',`${r.x-m} ${r.y-m} ${r.width+2*m} ${r.height+2*m}`);}catch{}});}
function filter(){const q=$('search').value.trim().toLowerCase();let count=0;for(const b of $('grid').children){const c=atoms.find(c=>c.id===b.dataset.id),match=(!q||(c.name+c.description+c.id+b.textContent).toLowerCase().includes(q))&&(activeGroup==='全部'||activeGroup===b.dataset.group);b.hidden=!match;if(match)count++;}$('count').textContent=`${count} / ${atoms.length}`;$('empty').hidden=count>0;}
for(const label of ['全部',...groups.map(g=>g.name)]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',String(label==='全部'));b.onclick=()=>{activeGroup=label;$('search').value='';$('groups').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();};$('groups').append(b);}
$('search').oninput=filter;filter();
function compose(){const example=examples[$('example').value];combined=true;$('name').textContent=example.name;$('description').textContent=example.description;$('editor-title').textContent='组合配置';$('props').value=JSON.stringify(example.items,null,2);$('catalog-edit').hidden=true;$('variants').replaceChildren();document.querySelectorAll('.part').forEach(b=>b.setAttribute('aria-pressed','false'));apply();}
$('apply').onclick=()=>{apply();$('variants').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));};$('reset').onclick=()=>combined?compose():select(current);
$('compose').onclick=compose;$('example').onchange=compose;
function save(text,type,name){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function standaloneSVG(){const svg=$('stage').querySelector('svg');if(!svg)throw Error('请先选择并显示一个部件。');const out=svg.cloneNode(true),b=svg.getBBox(),margin=14;out.setAttribute('viewBox',`${b.x-margin} ${b.y-margin} ${b.width+margin*2} ${b.height+margin*2}`);out.setAttribute('width',String(Math.ceil(b.width+margin*2)));out.setAttribute('height',String(Math.ceil(b.height+margin*2)));out.setAttribute('xmlns','http://www.w3.org/2000/svg');out.style.width='';out.style.height='';for(const img of out.querySelectorAll('image')){const src=img.getAttribute('href');if(!src||src.startsWith('data:'))continue;const url=new URL(src,assetBase);if(url.origin!==location.origin)throw Error('只能将当前项目中的图片嵌入 SVG');const response=await fetch(url);if(!response.ok)throw Error('图片读取失败，无法打包 SVG');const blob=await response.blob();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});img.setAttribute('href',data);}return '<?xml version="1.0" encoding="UTF-8"?>\n'+new XMLSerializer().serializeToString(out);}
$('download-svg').onclick=async()=>{try{save(await standaloneSVG(),'image/svg+xml;charset=utf-8',combined?'animation-parts-combined.svg':current.id+'.svg');}catch(e){$('error').textContent=e.message;}};
$('download-json').onclick=()=>{try{const props=JSON.parse($('props').value);save(JSON.stringify(combined?props:{component:current.id,props,effect:'none',soundEnabled:false},null,2),'application/json',combined?'animation-parts-combined.json':current.id+'-scene.json');}catch(e){$('error').textContent=e.message;}};
if(atoms.length)select(atoms.find(c=>c.id===new URL(location.href).searchParams.get('component'))||atoms[0]);else $('error').textContent='基础部件尚未构建，请刷新。';
