"""Build, confirm and check the opening plan the user approves before production.

The proposal JSON is the record; PLAN.md is the human view with real previews.
This script never starts production and never invents a user decision.
"""
import argparse
import hashlib
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path

from workflow_state import proposal_fingerprint, record_event

MARKER = '<!-- generated by opening_plan.py -->'
LIBRARY_KINDS = {'component': 'components', 'effect': 'effects', 'preset': 'presets',
                 'frame': 'frames', 'background': 'backgrounds', 'sound': 'sounds', 'icon': 'icons'}
FILE_KINDS = {'bgm', 'other'}
GALLERY = 'http://127.0.0.1:3031/catalog.html'


def load(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))


def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def within(root, relative):
    if not isinstance(relative, str) or not relative or Path(relative).is_absolute():
        raise ValueError(f'Expected project-relative path: {relative!r}')
    path = (root / relative).resolve()
    if not path.is_relative_to(root.resolve()):
        raise ValueError(f'Path escapes project: {relative}')
    return path


def project_path(root, value, label):
    """Accept a project-relative path or an existing absolute path."""
    candidate = Path(value).expanduser()
    if candidate.is_absolute():
        if not candidate.is_file():
            raise ValueError(f'{label}: 文件不存在 {candidate}')
        return candidate.resolve()
    path = within(root, value)
    if not path.is_file():
        raise ValueError(f'{label}: 文件不存在 {value}')
    return path


def paths_of(manifest):
    paths = manifest.get('paths', {})
    return paths.get('proposal') or 'planning/PROPOSAL.json', paths.get('plan') or 'planning/PLAN.md'


def library_entry(index, kind, ident):
    key = LIBRARY_KINDS[kind]
    for item in index.get(key, []):
        if item.get('id') == ident:
            return item
    return None


def library_file(library_root, entry, kind):
    if kind == 'component':
        candidate = library_root / 'snapshots' / f"{entry['id']}.png"
    elif kind == 'effect':
        candidate = library_root / 'snapshots' / 'effects' / f"{entry['id']}.png"
    elif kind == 'sound':
        source = entry.get('src') or f"assets/sfx/{entry['id']}.wav"
        candidate = library_root / source
    else:
        return None
    return candidate if candidate.is_file() else None


def gallery_link(kind, entry, item, stage_component):
    ident = entry.get('id')
    if kind == 'component':
        link = f'{GALLERY}?component={ident}'
        if item.get('presentation'):
            link += f"&presentation={item['presentation']}"
        if item.get('frame'):
            link += f"&frame-style={item['frame']}"
        if item.get('background'):
            link += f"&background-style={item['background']}"
        return link
    if kind == 'preset':
        return f'{GALLERY}?appearance={ident}'
    if kind == 'frame' and stage_component:
        return f'{GALLERY}?component={stage_component}&frame-style={ident}'
    if kind == 'background' and stage_component:
        return f'{GALLERY}?component={stage_component}&background-style={ident}'
    if kind == 'effect':
        return f'{GALLERY}?tab=effects'
    if kind == 'sound':
        return f'{GALLERY}?tab=sounds'
    if kind == 'icon':
        return f'{GALLERY}?tab=icons'
    return None


def variation_problems(proposal):
    variation = proposal.get('variation')
    if variation is None:
        return []
    if not isinstance(variation, dict):
        return ['variation 必须是对象。']
    problems = []
    for key in ('mode', 'seed', 'policy'):
        if not isinstance(variation.get(key), str) or not variation[key].strip():
            problems.append(f'variation.{key} 缺少有效说明。')
    allowed = variation.get('allowed_item_ids')
    known = {item.get('id') for item in proposal.get('items', []) if isinstance(item, dict)}
    if not isinstance(allowed, list) or not allowed or any(not isinstance(i, str) or i not in known for i in allowed):
        problems.append('variation.allowed_item_ids 必须引用本提案实际展示的候选项。')
    exceptions = variation.get('exceptions', [])
    if not isinstance(exceptions, list) or any(not isinstance(i, str) for i in exceptions):
        problems.append('variation.exceptions 必须是说明文字列表。')
    return problems


def resolve(root, manifest, proposal):
    """Resolve every declared item against the frozen library index."""
    library_root = Path(manifest.get('library', {}).get('source_root') or '').expanduser()
    index_path = manifest.get('paths', {}).get('library_index')
    index = load(within(root, index_path)) if index_path and within(root, index_path).is_file() else None
    items = proposal.get('items', [])
    if not isinstance(items, list) or not items:
        raise ValueError('策划案还没有任何候选项（items 为空）；先写 planning/PROPOSAL.json。')
    stage = next((i.get('library_id') for i in items if i.get('kind') == 'component' and i.get('library_id')), None)
    resolved, problems = [], variation_problems(proposal)
    seen = set()
    for raw in items:
        kind, ident = raw.get('kind'), raw.get('id')
        if not ident:
            problems.append('候选项缺少 id。')
            continue
        if ident in seen:
            problems.append(f'{ident}: 候选项 id 重复。')
            continue
        seen.add(ident)
        if kind not in LIBRARY_KINDS and kind not in FILE_KINDS:
            problems.append(f"{ident}: 未知候选项类型 {kind}")
            continue
        entry, preview, source = None, None, None
        if kind in LIBRARY_KINDS:
            if not index:
                problems.append(f'{ident}: 本期还没有冻结组件库索引 planning/LIBRARY.json')
                continue
            library_id = raw.get('library_id')
            entry = library_entry(index, kind, library_id) if library_id else None
            if entry is None:
                problems.append(f'{ident}: 组件库索引里没有 {kind} {library_id!r}')
                continue
            source = library_file(library_root, entry, kind)
            if raw.get('presentation') is not None:
                recipe = next((p for p in index.get('presentations', [])
                               if p.get('layout') == raw['presentation']
                               and p.get('component') == library_id), None)
                if kind != 'component' or recipe is None:
                    problems.append(f'{ident}: 当前冻结索引没有该组件的呈现配方 {raw["presentation"]!r}')
                    continue
                entry = {**entry, 'name': recipe['name']}
                # A default full-screen thumbnail must not stand in for a layout.
                candidate = library_root / 'snapshots' / 'presentations' / f'{recipe["layout"]}.png'
                source = candidate if candidate.is_file() else None
        explicit = raw.get('preview') or raw.get('file')
        try:
            if explicit:
                preview = project_path(root, explicit, ident)
            elif source:
                preview = source
        except ValueError as exc:
            problems.append(str(exc))
            continue
        if kind in FILE_KINDS and preview is None:
            problems.append(f'{ident}: 需要 file 指向本地候选文件')
            continue
        resolved.append({'item': raw, 'entry': entry, 'preview': preview,
                         'gallery': gallery_link(kind, entry or {}, raw, stage) if entry else None})
    return {'items': resolved, 'problems': problems, 'index': index, 'library_root': library_root}


def copy_previews(root, resolved):
    folder = within(root, 'planning/proposal/previews')
    folder.mkdir(parents=True, exist_ok=True)
    records = []
    for entry in resolved['items']:
        item, preview = entry['item'], entry['preview']
        record = {'item': item, 'id': item.get('id'), 'kind': item.get('kind'), 'library_id': item.get('library_id'),
                  'name': (entry['entry'] or {}).get('name') or item.get('name') or item.get('role') or item.get('id'),
                  'group': item.get('group'),
                  'gallery': entry['gallery'], 'preview': None, 'sha256': None, 'note': item.get('preview_note')}
        if preview is not None:
            target = folder / f"{item.get('kind')}-{item.get('id')}{preview.suffix.lower()}"
            if preview.resolve() != target.resolve():
                shutil.copy2(preview, target)
            record['preview'] = target.relative_to(root).as_posix()
            record['sha256'] = sha(target)
        records.append(record)
    return records


def media_block(root, record):
    if not record.get('preview'):
        return '（未附截图或试听文件：' + (record.get('note') or '需要先实际查看再交给用户') + '）'
    absolute = within(root, record['preview']).as_posix()
    name = record.get('name') or record.get('id')
    return f'![{name}]({absolute})'


def render(root, manifest, proposal, records, library_revision):
    structure = proposal.get('structure', [])
    style = proposal.get('style', {})
    confirmation = proposal.get('confirmation')
    lines = [MARKER, '']
    lines.append(f"# 开场策划案：{proposal.get('title') or manifest.get('title')}")
    lines.append('')
    if confirmation:
        lines.append(f"**状态：已由用户确认**（{confirmation.get('confirmed_at')}）")
        lines.append('')
        lines.append(f"- 用户原话或消息摘要：{confirmation.get('by_user')}")
        if confirmation.get('scope'):
            lines.append(f"- 范围：{confirmation['scope']}")
        if confirmation.get('answers'):
            for key, value in confirmation['answers'].items():
                lines.append(f'- {key}：{value}')
    else:
        lines.append('**状态：待用户确认。** 确认前不写编导稿、分镜稿，也不开始制作。')
    lines.append('')
    lines.append(f"组件库版本：`{(library_revision or {}).get('id')} {(library_revision or {}).get('version')}` "
                 f"revision `{(library_revision or {}).get('revision', '未知')}`")
    lines.append('')
    lines.append('## 一、本期讲什么')
    lines.append('')
    for key, label in [('audience', '受众'), ('goal', '要讲清的一件事'), ('opening', '开头承诺'), ('ending', '结尾带走')]:
        if proposal.get(key):
            lines.append(f'- {label}：{proposal[key]}')
    lines.append('')
    if structure:
        lines.append('| 段落 | 对应声音 | 讲解任务 | 观众变化 |')
        lines.append('| --- | --- | --- | --- |')
        for group in structure:
            lines.append(f"| {group.get('id')} {group.get('part', '')} | {group.get('narration', '')} | "
                         f"{group.get('intent', '')} | {group.get('viewer_delta', '')} |")
        lines.append('')
    lines.append('## 二、整体视觉')
    lines.append('')
    for key, label in [('palette', '色板'), ('frame_default', '默认外框'), ('background_default', '默认背景'),
                       ('typography', '字体与字号'), ('captions', '字幕策略'), ('notes', '其他约束')]:
        if style.get(key):
            lines.append(f'- {label}：{style[key]}')
    lines.append('')
    variation = proposal.get('variation')
    if isinstance(variation, dict):
        lines.extend(['### 动态多样性与轮换范围', '',
                      f"- 编排方式：{variation.get('mode', '')}",
                      f"- 固定随机种子：`{variation.get('seed', '')}`",
                      f"- 轮换规则：{variation.get('policy', '')}",
                      '- 已展示候选范围：' + '、'.join(variation.get('allowed_item_ids', []))])
        for exception in variation.get('exceptions', []):
            lines.append(f'- 例外或锁定：{exception}')
        lines.extend(['', '在已确认候选池和规则内编排；具体指定的处理保持锁定。新候选或方向变化仍需更新方案。', ''])
    lines.append('## 三、逐段画面方案')
    lines.append('')
    if any(group.get('visual_source') or group.get('visual_plan') or group.get('material_ref')
           or group.get('material_status') for group in structure):
        def cell(value):
            return str(value or '').replace('|', '&#124;').replace('\r\n', '\n').replace('\n', '<br>')

        lines.append('| 段落 | 主素材来源 | 画面职责与混剪安排 | 素材/预览 | 状态 |')
        lines.append('| --- | --- | --- | --- | --- |')
        for group in structure:
            values = [group.get('id'), group.get('visual_source'), group.get('visual_plan'),
                      group.get('material_ref'), group.get('material_status')]
            lines.append('| ' + ' | '.join(cell(value) for value in values) + ' |')
        lines.append('')
        lines.append('以下为按需采用的辅助组件；主素材段落不要求配组件。')
        lines.append('')
    by_group = {}
    for record in records:
        if record.get('kind') in {'component', 'preset'}:
            by_group.setdefault(record.get('group') or '全片', []).append(record)
    lines.append('| 段落 | 用途 | 组件 | 动画效果 | 背景 | 边框 | 音效 |')
    lines.append('| --- | --- | --- | --- | --- | --- | --- |')
    order = [group.get('id') for group in structure] or list(by_group)
    for extra in by_group:
        if extra not in order:
            order.append(extra)
    for gid in order:
        rows = by_group.get(gid, [])
        for record in rows:
            item = record['item']
            label = f"{record.get('name') or ''} `{record.get('library_id') or record.get('id')}`"
            lines.append(f"| {gid} | {item.get('role', '')} | {label} | {item.get('effect', '')} | "
                         f"{item.get('background') or style.get('background_default', '')} | "
                         f"{item.get('frame') or style.get('frame_default', '')} | "
                         f"{', '.join(item.get('sound', []))} |")
    lines.append('')
    lines.append('## 四、候选项明细')
    lines.append('')
    for record in [r for r in records if r.get('kind') not in FILE_KINDS and r.get('kind') != 'sound']:
        item = record['item']
        lines.append(f"### {item.get('role') or item.get('id')}：{record.get('name') or ''}")
        lines.append('')
        lines.append(media_block(root, record))
        lines.append('')
        lines.append(f"- 库中 ID：`{record.get('library_id') or item.get('id')}`（{record.get('kind')}）")
        if item.get('effect'):
            lines.append(f"- 动画效果：`{item['effect']}`")
        if item.get('why'):
            lines.append(f"- 选择理由：{item['why']}")
        if item.get('alternatives'):
            lines.append(f"- 备选：{', '.join(str(a) for a in item['alternatives'])}")
        if record.get('gallery'):
            lines.append(f"- 画廊链接：{record['gallery']}")
        lines.append('')
    lines.append('## 五、声音与音乐')
    lines.append('')
    sounds = [r for r in records if r.get('kind') == 'sound']
    music = [r for r in records if r.get('kind') in FILE_KINDS]
    for record in sounds + music:
        lines.append(f"### {record.get('name') or record.get('id')}")
        lines.append('')
        lines.append(media_block(root, record))
        lines.append('')
        if record['item'].get('role'):
            lines.append(f"- 用途：{record['item']['role']}")
        if record['item'].get('license'):
            lines.append(f"- 许可：{record['item']['license']}")
        lines.append('')
    if not sounds and not music:
        lines.append('（本阶段还没有声音候选）')
        lines.append('')
    lines.append('## 六、需要你拍板的问题')
    lines.append('')
    questions = proposal.get('questions', [])
    if questions:
        lines.append('| 编号 | 问题 | 推荐默认 | 你的回答 |')
        lines.append('| --- | --- | --- | --- |')
        for question in questions:
            lines.append(f"| {question.get('id')} | {question.get('text', '')} | {question.get('default', '')} | "
                         f"{question.get('answer', '待回答')} |")
    else:
        lines.append('（无待定问题；如认可当前方案，回复“确认”即可）')
    lines.append('')
    lines.append('## 七、缺口与等待项')
    lines.append('')
    gaps = proposal.get('gaps', [])
    if gaps:
        lines.append('| 缺口 | 类型 | 谁产出 | 当前状态 |')
        lines.append('| --- | --- | --- | --- |')
        for gap in gaps:
            lines.append(f"| {gap.get('need', '')} | {gap.get('type', '')} | {gap.get('owner', '')} | "
                         f"{gap.get('status', '')} |")
    else:
        lines.append('（本期没有待生成或待录制的缺口）')
    lines.append('')
    lines.append('## 八、下一步')
    lines.append('')
    if confirmation:
        lines.append('已确认。下一步写编导稿与分镜稿，按本方案进入制作。')
    else:
        lines.append('请逐项回复上面第六节的问题，或直接说“都按默认”。确认后才开始编导稿、分镜稿与制作。')
    lines.append('')
    return '\n'.join(lines)


def write_plan(root, manifest, proposal, records):
    plan_rel = paths_of(manifest)[1]
    target = within(root, plan_rel)
    if target.is_file() and not args_force_ok(target):
        return None
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(root, manifest, proposal, records, manifest.get('library')), encoding='utf-8')
    return target


FORCE = {'value': False}


def args_force_ok(target):
    if FORCE['value']:
        return True
    text = target.read_text(encoding='utf-8-sig')
    return MARKER in text or text.startswith('# 本期开场策划案')


def build(args):
    root = Path(args.project).resolve()
    manifest = load(root / 'PROJECT.json')
    proposal_rel, plan_rel = paths_of(manifest)
    proposal_path = within(root, proposal_rel)
    if not proposal_path.is_file():
        raise ValueError(f'缺少 {proposal_rel}；先写候选项再生成策划案。')
    proposal = load(proposal_path)
    result = resolve(root, manifest, proposal)
    if result['problems']:
        return {'ok': False, 'problems': result['problems'],
                'note': '候选项没有全部解析成功；先修好再交给用户，不要跳过缺失项。'}
    records = copy_previews(root, result)
    resolved_rel = 'planning/proposal/RESOLVED.json'
    save(within(root, resolved_rel), {
        'generated_at': datetime.now().astimezone().isoformat(),
        'library': manifest.get('library'),
        'items': records,
    })
    plan_path = write_plan(root, manifest, proposal, records)
    if plan_path is None:
        return {'ok': False, 'error': f'{plan_rel} 不是本脚本生成的内容；确认覆盖时加 --force。'}
    current_fingerprint = proposal_fingerprint(proposal)
    existing_confirmation = proposal.get('confirmation') or {}
    event_type = 'opening_plan_refreshed' if (
        existing_confirmation.get('proposal_fingerprint') == current_fingerprint
    ) else 'opening_plan_built'
    record_event(root, event_type, phase='opening_plan', details={
        'proposal_fingerprint': current_fingerprint,
        'preview_count': sum(1 for record in records if record.get('preview')),
        'confirmed': bool(existing_confirmation),
    })
    missing = [record['id'] for record in records if not record.get('preview')]
    return {'ok': True, 'plan': plan_path.relative_to(root).as_posix(),
            'previews': sum(1 for record in records if record.get('preview')),
            'without_preview': missing,
            'confirmed': bool(proposal.get('confirmation')),
            'next': '把 PLAN.md 和问题清单交给用户，停在这里等确认；确认前不要写编导稿、分镜稿或开始制作。',
            'note': '预览文件已复制到 planning/proposal/previews/；画廊链接需要本机 3031 预览服务。'}


def confirm(args):
    root = Path(args.project).resolve()
    manifest = load(root / 'PROJECT.json')
    proposal_rel, _ = paths_of(manifest)
    proposal_path = within(root, proposal_rel)
    if not proposal_path.is_file():
        raise ValueError(f'缺少 {proposal_rel}；没有策划案可确认。')
    proposal = load(proposal_path)
    if not isinstance(args.by_user, str) or not args.by_user.strip():
        raise ValueError('必须用 --by-user 记录用户实际回复，不能代填确认。')
    answer_map = {}
    for question in proposal.get('questions', []):
        text = str(question.get('answer', '')).strip()
        if not text or text == '待回答':
            if not args.allow_open_questions:
                raise ValueError(f"问题 {question.get('id')} 还没有回答；先确认答案，或明确用 --allow-open-questions 记录仍有待定项。")
            text = '待定（用户未逐条回答）'
        answer_map[str(question.get('id'))] = text
    current_fingerprint = proposal_fingerprint(proposal)
    confirmation = {'confirmed_at': datetime.now().astimezone().isoformat(), 'by_user': args.by_user.strip(),
                    'scope': args.scope, 'answers': answer_map, 'changes': args.change,
                    'proposal_fingerprint': current_fingerprint}
    if proposal.get('confirmation'):
        history = proposal.get('confirmation_history', [])
        history.append(proposal['confirmation'])
        proposal['confirmation_history'] = history
    proposal['confirmation'] = {k: v for k, v in confirmation.items() if v not in (None, [], {})}
    save(proposal_path, proposal)
    result = resolve(root, manifest, proposal)
    if result['problems']:
        return {'ok': False, 'problems': result['problems'], 'note': '确认已记录，但候选项仍有解析问题。'}
    records = copy_previews(root, result)
    save(within(root, 'planning/proposal/RESOLVED.json'), {
        'generated_at': datetime.now().astimezone().isoformat(),
        'library': manifest.get('library'),
        'items': records,
    })
    write_plan(root, manifest, proposal, records)
    record_event(root, 'opening_plan_confirmed', phase='directing', details={
        'proposal_fingerprint': current_fingerprint,
        'scope': args.scope,
        'answers': answer_map,
    })
    return {'ok': True, 'confirmed_at': proposal['confirmation']['confirmed_at'],
            'by_user': proposal['confirmation']['by_user'],
            'next': '确认已记录。现在可以写编导稿与分镜稿，再进入 HyperFrames 制作。'}


def check_plan(root, manifest, strict, check_scene_bindings=True):
    """Called by episode.py check; new projects gate production on this."""
    errors, warnings = [], []

    def issue(message):
        (errors if strict else warnings).append(message)

    if manifest.get('settings', {}).get('opening_plan_contract') != 'user-confirmed-v1':
        return {'errors': errors, 'warnings': warnings}
    proposal_rel, plan_rel = paths_of(manifest)
    proposal_path = within(root, proposal_rel)
    plan_path = within(root, plan_rel)
    if not proposal_path.is_file():
        issue(f'开场策划案尚未建立：缺少 {proposal_rel}；先出候选方案并取得用户确认。')
        return {'errors': errors, 'warnings': warnings}
    if not plan_path.is_file() or not plan_path.read_text(encoding='utf-8-sig').strip():
        issue(f'开场策划案文档缺失：{plan_rel}。')
    try:
        proposal = load(proposal_path)
        confirmation = proposal.get('confirmation') or {}
        if not confirmation.get('by_user') or not confirmation.get('confirmed_at'):
            issue('开场策划案还没有用户确认记录（PROPOSAL.json.confirmation）。')
        current_fingerprint = proposal_fingerprint(proposal)
        saved_fingerprint = confirmation.get('proposal_fingerprint')
        if saved_fingerprint and saved_fingerprint != current_fingerprint:
            issue('用户确认后策划案内容发生变化；必须重新 build 并取得新的用户确认，不能沿用旧确认。')
        elif not saved_fingerprint and confirmation:
            warnings.append('旧项目确认记录没有 proposal_fingerprint；本次按兼容模式检查，后续重新确认会补上。')
        resolved_path = within(root, 'planning/proposal/RESOLVED.json')
        if not resolved_path.is_file():
            issue('候选项预览尚未生成：缺少 planning/proposal/RESOLVED.json，运行 opening_plan.py build。')
        else:
            for record in load(resolved_path).get('items', []):
                relative = record.get('preview')
                if not relative:
                    if strict:
                        warnings.append(f"{record.get('id')}: 候选项没有截图或试听文件。")
                    continue
                path = within(root, relative)
                if not path.is_file():
                    errors.append(f"{record.get('id')}: 预览文件缺失 {relative}")
                elif record.get('sha256') and sha(path) != record['sha256']:
                    errors.append(f"{record.get('id')}: 预览文件与生成时不一致，重新 build 后再确认。")
        result = resolve(root, manifest, proposal)
        for problem in result['problems']:
            issue(problem)
        frozen = manifest.get('library', {}).get('revision')
        if result['index'] and frozen and result['index'].get('library', {}).get('revision') != frozen:
            warnings.append('组件库索引已更新；策划案预览可能来自旧版本，核对后重新 build。')
        # A bind/prepare operation runs after the proposal is confirmed but
        # before the new EDIT mount exists.  It still needs every proposal,
        # preview and fingerprint check; only the future scene-binding check
        # is deferred until episode.py ready/review.
        if strict and check_scene_bindings:
            edit = load(within(root, manifest['paths']['edit']))
            scenes = {scene.get('id'): scene for scene in edit.get('scenes', [])}
            for entry in result['items']:
                item = entry['item']
                for sid in item.get('scenes', []) or []:
                    scene = scenes.get(sid)
                    if scene is None:
                        errors.append(f"{item.get('id')}: 策划案引用的镜头 {sid} 不在 EDIT 中。")
                        continue
                    if item.get('kind') != 'component' or not item.get('library_id'):
                        continue
                    bound = {b.get('component_id') for b in scene.get('component_bindings', [])}
                    if item['library_id'] not in bound:
                        errors.append(f"{sid}: 实际绑定与已确认策划案不一致；确认的方案是 {item['library_id']}，"
                                      f"实际为 {', '.join(sorted(x for x in bound if x)) or '无'}。")
    except (ValueError, OSError, KeyError, TypeError) as exc:
        errors.append(f'开场策划案检查失败：{exc}')
    return {'errors': errors, 'warnings': warnings}


def check(args):
    root = Path(args.project).resolve()
    manifest = load(root / 'PROJECT.json')
    strict = args.strict
    result = check_plan(root, manifest, strict)
    proposal_rel, plan_rel = paths_of(manifest)
    proposal_path = within(root, proposal_rel)
    confirmation = load(proposal_path).get('confirmation') if proposal_path.is_file() else None
    report = {'ok': not result['errors'], 'strict': strict, 'proposal': proposal_rel, 'plan': plan_rel,
              'confirmed': bool(confirmation), 'confirmed_at': (confirmation or {}).get('confirmed_at'),
              'errors': result['errors'], 'warnings': result['warnings'],
              'note': '检查记录与预览文件；不判断画面好坏，也不代替用户决定。'}
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report['ok'] else 1


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    for name in ('build', 'confirm', 'check'):
        sub = commands.add_parser(name)
        sub.add_argument('project')
        if name == 'build':
            sub.add_argument('--force', action='store_true', help='覆盖不是本脚本生成的手写 PLAN.md。')
        if name == 'confirm':
            sub.add_argument('--by-user', required=True, help='用户实际回复的原话或消息摘要。')
            sub.add_argument('--scope', help='本次确认覆盖的范围。')
            sub.add_argument('--change', action='append', default=[], help='本次相对上一版的改动，可重复。')
            sub.add_argument('--allow-open-questions', action='store_true',
                             help='仅当用户明确表示部分问题待定时使用。')
        if name == 'check':
            sub.add_argument('--strict', action='store_true',
                             help='按制作阶段判定：未确认即失败。')
    args = parser.parse_args()
    FORCE['value'] = getattr(args, 'force', False)
    try:
        if args.command == 'build':
            result = build(args)
        elif args.command == 'confirm':
            result = confirm(args)
        else:
            return check(args)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0 if result.get('ok') else 1
    except (ValueError, OSError, KeyError, TypeError) as exc:
        print(json.dumps({'ok': False, 'error': str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
