import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import puppeteer from 'puppeteer-core';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(await readFile(resolve(root,'manifest.json'),'utf8'));
const filter=process.argv.find(a=>a.startsWith('--only='))?.slice(7).split(',');
const entries=[...manifest.components.map(c=>({...c,kind:'component'})),...manifest.effects.map(e=>({...e,kind:'effect'}))].filter(c=>!filter||filter.includes(c.id));
await mkdir(resolve(root,'snapshots/effects/proof'),{recursive:true});
const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files'],protocolTimeout:30000});
const reports=[];let pointer=0;
async function capture(c){const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.setViewport({width:c.width,height:c.height,deviceScaleFactor:1});await page.goto(pathToFileURL(resolve(root,c.preview)).href,{waitUntil:'load'});await page.waitForFunction('window.__componentReady===true');await page.evaluate(()=>document.fonts.ready);const time=c.kind==='effect'?(c.previewTime??1.9):(manifest.effects.find(e=>e.id===c.defaultEffect)?.previewTime??0);await page.evaluate(t=>window.previewAPI.seek(t),time);await page.screenshot({path:resolve(root,`snapshots/${c.kind==='effect'?'effects/':''}${c.id}.png`)});const layout=await page.evaluate(()=>{const root=document.getElementById('root'),bound=root.getBoundingClientRect(),out=[],text=[];for(const e of root.querySelectorAll('*')){const s=getComputedStyle(e);if(s.display==='none'||s.visibility==='hidden'||s.opacity==='0')continue;const r=e.getBoundingClientRect();if(r.width<1||r.height<1)continue;if(r.left<bound.left-.6||r.top<bound.top-.6||r.right>bound.right+.6||r.bottom>bound.bottom+.6){if(!e.closest('[data-motion="scroll"]')&&!e.closest('svg')&&!e.matches('.fx-layer *'))out.push({tag:e.tagName,cls:e.className?.baseVal??e.className,text:e.textContent.slice(0,60),box:[r.x,r.y,r.width,r.height]});}if(e.childElementCount===0&&e.textContent.trim()&&e.clientWidth&&e.scrollWidth>e.clientWidth+2&&s.overflowX==='visible'&&!e.closest('svg'))text.push({tag:e.tagName,cls:e.className,text:e.textContent.slice(0,70),scroll:e.scrollWidth,width:e.clientWidth});}return {outside:out.slice(0,15),textOverflow:text.slice(0,15),textLength:root.innerText.length,effectTargets:Number(root.dataset.effectTargets||0),dimensions:[bound.width,bound.height]};});if(c.kind==='effect'){for(const [label,t] of [['start',0],['end',7.95],['middle',c.previewTime??1.9]]){await page.evaluate(t=>window.previewAPI.seek(t),t);await page.screenshot({path:resolve(root,`snapshots/effects/proof/${c.id}-${label}.png`)});}}reports.push({id:c.id,kind:c.kind,errors,...layout});await page.close();console.log(`${c.kind}: ${c.id} (${errors.length} runtime errors)`);}
try{await Promise.all(Array.from({length:1},async()=>{while(pointer<entries.length){const entry=entries[pointer++];await capture(entry);}}));}finally{await browser.close();}
await mkdir(resolve(root,'reports'),{recursive:true});await writeFile(resolve(root,filter?'reports/snapshot-targeted.json':'reports/snapshots.json'),JSON.stringify(reports,null,2));
console.log(`Captured ${reports.length} previews, ${reports.filter(r=>r.errors.length).length} runtime failures.`);
