// Independent checks. No video rendering, cloud service, or persistent server.
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath,pathToFileURL} from 'node:url';
import puppeteer from 'puppeteer-core';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const args=new Set(process.argv.slice(2));
const priorReport=args.has('--example-only')?JSON.parse(await fs.readFile(path.join(root,'reports/audio-verification.json'),'utf8')):null;
const report={generatedAt:new Date().toISOString(),noVideoRendered:true,assets:[],tracks:[],previews:[],templates:[],gallery:[],sourceEvidence:[],failures:[],limitations:['Playback lifecycle and decoded PCM are measured; these checks do not claim a human listening test or a rendered-video listening test.']};
function check(ok,message){if(!ok)report.failures.push(message);return Boolean(ok);}
const closeTo=(a,b,tolerance=.16)=>Number.isFinite(a)&&Math.abs(a-b)<=tolerance;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));

export function measureWav(bytes){
 if(bytes.toString('ascii',0,4)!=='RIFF'||bytes.toString('ascii',8,12)!=='WAVE')throw Error('Not a RIFF WAVE');
 let format,data;for(let p=12;p+8<=bytes.length;){const id=bytes.toString('ascii',p,p+4),size=bytes.readUInt32LE(p+4);if(p+8+size>bytes.length)throw Error('Truncated WAV chunk');if(id==='fmt ')format={encoding:bytes.readUInt16LE(p+8),channels:bytes.readUInt16LE(p+10),sampleRate:bytes.readUInt32LE(p+12),blockAlign:bytes.readUInt16LE(p+20),bits:bytes.readUInt16LE(p+22)};if(id==='data')data=bytes.subarray(p+8,p+8+size);p+=8+size+(size%2);}
 if(!format||!data)throw Error('Missing WAV fmt/data chunk');
 if(format.encoding!==1||![16,24,32].includes(format.bits))throw Error('Expected integer PCM WAV, got '+JSON.stringify(format));
 const stride=format.bits/8,samples=data.length/stride;let peak=0,squares=0,sum=0,clipped=0,nonzero=0;const buckets=new Float64Array(Math.ceil(samples/format.channels/format.sampleRate*100));
 for(let p=0,i=0;p<data.length;p+=stride,i++){let n=stride===2?data.readInt16LE(p)/32768:stride===3?data.readIntLE(p,3)/8388608:data.readInt32LE(p)/2147483648;peak=Math.max(peak,Math.abs(n));squares+=n*n;sum+=n;if(Math.abs(n)>=.999)clipped++;if(n!==0)nonzero++;const b=Math.floor(i/format.channels/format.sampleRate*100);buckets[b]=Math.max(buckets[b],Math.abs(n));}
 const first=buckets.findIndex(v=>v>.0005),last=buckets.findLastIndex(v=>v>.0005);
 return {...format,duration:data.length/format.blockAlign/format.sampleRate,samples,peak,rms:Math.sqrt(squares/samples),dc:sum/samples,clipped,nonzero,firstSignal:first<0?null:first/100,lastSignal:last<0?null:(last+1)/100,buckets:[...buckets]};
}
function compact(stats){const {buckets,...rest}=stats;return rest;}
async function inspectWav(id,src,silent=false){try{const stats=measureWav(await fs.readFile(path.resolve(root,src)));check(stats.clipped===0,id+': PCM clipping detected');check(stats.peak<=.98,id+': insufficient peak headroom');check(stats.sampleRate>=44100,id+': expected at least 44.1 kHz');check(silent?stats.nonzero===0:stats.rms>.0001,id+(silent?': silence track contains signal':': WAV is silent'));return {id,src,...compact(stats),buckets:stats.buckets};}catch(e){check(false,id+': '+e.message);return {id,src,error:e.message};}}

const manifest=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));
const {effects}=await import(pathToFileURL(path.join(root,'animations.mjs')).href);
let sounds=[];try{const module=await import(pathToFileURL(path.join(root,'sound-assets.mjs')).href);sounds=module.sounds||[];}catch(e){check(false,'sound-assets.mjs: '+e.message);}
check(sounds.length>0,'No sound asset inventory');
for(const sound of sounds){const src=sound.src||sound.path;const stats=await inspectWav(sound.id,src);report.assets.push({...stats,buckets:undefined});if(sound.duration!=null&&stats.duration!=null)check(closeTo(stats.duration,Number(sound.duration),.03),sound.id+': duration metadata differs from WAV');}
for(const effect of manifest.effects){const src=typeof effect.soundTrack==='string'?effect.soundTrack:effect.soundTrack?.src||`assets/sfx/tracks/${effect.id}.wav`;const stats=await inspectWav(effect.id,src,Boolean(effect.silent));const definition=effects.find(e=>e.id===effect.id);const cues=definition?.cueHints||[];check(effect.silent?cues.length===0:cues.length>0,effect.id+': cue timing or silent-background contract');check(closeTo(stats.duration,Number(effect.duration||8),.03),effect.id+': track length differs from animation');for(const cue of cues){check(sounds.some(s=>s.id===cue.sound),effect.id+': cue refers to unknown sound '+cue.sound);check(Number.isFinite(cue.at)&&cue.at>=0&&cue.at<Number(effect.duration||8),effect.id+': invalid cue time');if(stats.buckets){const a=Math.floor(cue.at*100),b=Math.ceil(Math.min(Number(effect.duration||8),cue.at+.6)*100);check(stats.buckets.slice(a,b).some(x=>x>.0005),effect.id+': no measurable sound near cue '+cue.at);}}if(cues.length&&stats.firstSignal!==null)check(stats.firstSignal>=Math.min(...cues.map(c=>c.at))-.03,effect.id+': sound precedes first authored cue');report.tracks.push({...stats,buckets:undefined,cueCount:cues.length});}
const silence=await inspectWav('none','assets/sfx/tracks/none.wav',true);report.tracks.push({...silence,buckets:undefined});

// These source assertions prevent a "browser makes sound, export loses it" regression.
const cli=await fs.readFile(path.join(root,'node_modules/hyperframes/dist/cli.js'),'utf8');
// Execute the installed compiler's own parser and source-mutation detector in an
// isolated VM, without loading the CLI entry point or creating a render job.
function moduleSection(marker){const start=cli.indexOf(marker);if(start<0)throw Error('Installed module missing: '+marker);const end=cli.indexOf('\n// ',start+marker.length);return cli.slice(start,end<0?undefined:end);}
let detectSourceMutations;
try{const acorn=moduleSection('// ../../node_modules/.bun/acorn@8.17.0/node_modules/acorn/dist/acorn.mjs'),walk=moduleSection('// ../../node_modules/.bun/acorn-walk@8.3.5/node_modules/acorn-walk/dist/walk.mjs'),start=cli.indexOf('function parseProgram2(script)'),end=cli.indexOf('function resolveAliasDisplayName(',start);const context=vm.createContext({});vm.runInContext('var __getOwnPropNames=Object.getOwnPropertyNames;var __esm=(fn,res)=>function(){return fn&&(res=(0,fn[__getOwnPropNames(fn)[0]])(fn=0)),res;};\n'+acorn+'\n'+walk+'\n'+cli.slice(start,end)+'\ninit_acorn();init_walk();globalThis.detectSourceMutations=extractMediaSrcMutations;',context,{timeout:3000});detectSourceMutations=script=>context.detectSourceMutations(script);const proof=detectSourceMutations("const sfx=document.getElementById('proof-sfx');sfx.src=ComponentSoundRuntime.trackURL(effectId);");check(proof.length===1&&proof[0].selector==='#proof-sfx','Actual compiler AST detector did not recognize audio source binding');report.sourceEvidence.push({name:'actual_installed_ast_probe',ok:proof.length===1,proof});}catch(e){check(false,'Compiler detector execution: '+e.message);}
const sourceChecks=[
 ['static_audio_discovery',cli.includes('document2.querySelectorAll("audio[id]")')],
 ['script_src_mutation_probe',cli.includes('const hasInsertedMedia = hasRuntimeMediaChanges(compiled.html)')],
 ['browser_source_reconciliation',cli.includes('const sourceChanged = existing.src !== src')],
 ['muted_track_pruning',cli.includes('pruneMutedBrowserMedia(composition, browserMedia, existingAudioIds)')]
];for(const [name,ok] of sourceChecks){report.sourceEvidence.push({name,ok});check(ok,'Installed HyperFrames source contract changed: '+name);}
function installedFunction(name){const match=new RegExp('(?:async )?function '+name+'\\(').exec(cli);if(!match)throw Error('Installed function missing: '+name);const tail=cli.slice(match.index),end=tail.slice(1).search(/\n(?:(?:async )?function |var |\/\/ )/);return end<0?tail:tail.slice(0,end+1);}
// Exercise the installed engine's exact discovery/reconciliation implementation,
// without calling capture, extraction, mix or encoding. The prior authored media
// list models a compiled composition; this is not a full compile/render test.
const discoverySource=installedFunction('discoverMediaFromBrowser');
const reconciliationStart=cli.indexOf('    const browserMedia = await discoverMediaFromBrowser(session.page);');
const reconciliationEnd=cli.indexOf('    if (composition.audios.length > 0)',reconciliationStart);
const reconciliationSource=cli.slice(reconciliationStart,reconciliationEnd);
const renderIdsSource=moduleSection('// ../core/dist/compiler/mediaRenderIds.js');
const engineContext=vm.createContext({});
vm.runInContext(['parseNumeric2','parseStrictFiniteTimingNumber','readMediaStart','resolveBrowserMediaEnd','projectBrowserEndToCompositionTimeline','reconcileBrowserMediaEnd','pruneMutedBrowserMedia'].map(installedFunction).join('\n')+'\n'+discoverySource+'\nconst BROWSER_MEDIA_EPSILON=1e-4;globalThis.reconcile=async function(page,composition,url){const session={page},fileServer={url};const assertNotAborted=()=>{};'+reconciliationSource+'return {composition,browserMedia};};',engineContext,{timeout:3000});

const fixtures=new Map();const safeAttr=v=>String(v).replaceAll('&','&amp;').replaceAll("'",'&#39;').replaceAll('"','&quot;');
function hostSlot(id,component,vars,start=0){return `<div id="${id}" data-composition-id="${component}" data-composition-src="/compositions/${component}.html" data-variable-values='${safeAttr(JSON.stringify(vars))}' data-start="${start}" data-duration="8" data-track-index="1" data-width="1280" data-height="800"></div>`;}
function host(slots){return `<!doctype html><html><head><meta charset="UTF-8"><script src="/vendor/gsap.min.js"></script></head><body><div id="audio-host" data-composition-id="audio-host" data-width="1920" data-height="1080" data-duration="12">${slots}</div><script>window.__timelines={'audio-host':gsap.timeline({paused:true})};</script><script src="/vendor/hyperframe-runtime.js"></script></body></html>`;}
const typeEffect=manifest.effects.find(e=>e.id==='typewriter')||manifest.effects[0];
fixtures.set('/audio-instances.html',host(hostSlot('instance-a',typeEffect.component,{effect:typeEffect.id,soundGain:.31,soundEnabled:true},2)+hostSlot('instance-b',typeEffect.component,{effect:'fade-in',soundGain:.63,soundEnabled:true},4)));
fixtures.set('/audio-disabled.html',host(hostSlot('instance-off',typeEffect.component,{effect:typeEffect.id,soundEnabled:false},0)+hostSlot('instance-zero',typeEffect.component,{effect:typeEffect.id,soundGain:0},0)));
let browser,server;const serverErrors=[];
try{
 if(!args.has('--assets-only')){
  server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/favicon.ico'){res.writeHead(204).end();return;}if(fixtures.has(url.pathname)){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fixtures.get(url.pathname));return;}const filename=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(path.relative(root,filename).startsWith('..'))throw Error('Outside fixture root');const bytes=await fs.readFile(filename),ext=path.extname(filename),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.wav':'audio/wav','.png':'image/png'}[ext]||'application/octet-stream';res.setHeader('Content-Type',mime);res.setHeader('Cache-Control','no-store');res.setHeader('Accept-Ranges','bytes');const range=req.headers.range?.match(/bytes=(\d+)-(\d*)/);if(range){const start=Number(range[1]),end=range[2]?Math.min(bytes.length-1,Number(range[2])):bytes.length-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${bytes.length}`,'Content-Length':end-start+1});res.end(bytes.subarray(start,end+1));}else res.end(bytes);}catch(e){serverErrors.push({url:req.url,message:e.message});res.writeHead(404).end('Missing fixture');}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
  browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required'],protocolTimeout:60000});
  const page=await browser.newPage();await page.setViewport({width:1500,height:1000});
  const readAudio=()=>page.evaluate(()=>{const a=document.querySelector('audio[data-component-sfx]')||document.querySelector('audio[id$="-sfx"]')||document.querySelector('audio');return a?{id:a.id,src:a.currentSrc||a.src,paused:a.paused,time:a.currentTime,duration:a.duration,muted:a.muted,volume:a.volume,start:Number(a.dataset.start||0),mediaStart:Number(a.dataset.mediaStart||0),count:document.querySelectorAll('audio').length}:null;});
  for(const effect of args.has('--example-only')||args.has('--skip-previews')?[]:manifest.effects){
   const failuresBefore=report.failures.length,errors=[];const listener=e=>errors.push(e.message);page.on('pageerror',listener);
   try{
    await page.goto(base+'/'+effect.preview);await page.waitForFunction(()=>window.__componentReady===true&&[...document.querySelectorAll('audio')].some(a=>Number.isFinite(a.duration)&&a.readyState>=2),{timeout:12000});
    const initial=await readAudio();check(initial&&initial.count===1,effect.id+': expected exactly one consolidated audio track');check(initial.paused,effect.id+': preview auto-started sound');check(initial.src.endsWith('/'+effect.id+'.wav'),effect.id+': selected audio does not match effect');
    await page.evaluate(async()=>{window.previewAPI.seek(.82);await window.previewAPI.play();});await page.waitForFunction(()=>{const a=document.querySelector('audio');return a&&!a.paused&&a.currentTime>.84;},{timeout:2500});const played=await readAudio();const visualTime=await page.evaluate(()=>window.previewAPI.time());check(!played.paused&&played.time>.84,effect.id+': audio did not advance while playing');check(Math.abs(played.time-visualTime)<=.19,effect.id+': sound and animation drift exceeds 190 ms');
    await page.evaluate(()=>window.previewAPI.pause());const paused=await readAudio();await wait(100);const stable=await readAudio();check(stable.paused&&closeTo(paused.time,stable.time,.025),effect.id+': pause left advancing audio');
    await page.evaluate(()=>window.previewAPI.seek(2.1));await wait(25);const sought=await readAudio();check(sought.paused&&closeTo(sought.time,2.1,.07),effect.id+': scrub did not seek and pause sound');
    await page.evaluate(()=>window.previewAPI.seek(.45));const backwards=await readAudio();check(backwards.paused&&closeTo(backwards.time,.45,.07),effect.id+': backward scrub audio mismatch');
    await page.evaluate(()=>window.previewAPI.restart());await wait(90);const restarted=await readAudio();check(!restarted.paused&&restarted.time<.35,effect.id+': replay did not restart sound');
    const hasControls=await page.evaluate(()=>typeof window.previewAPI.setSoundEnabled==='function'&&typeof window.previewAPI.setSoundGain==='function');check(hasControls,effect.id+': sound controls absent');
    if(hasControls){await page.evaluate(()=>window.previewAPI.setSoundEnabled(false));const muted=await readAudio();check(muted.muted||muted.paused||muted.volume===0,effect.id+': sound disable failed');await page.evaluate(()=>{window.previewAPI.setSoundEnabled(true);window.previewAPI.setSoundGain(.27);});const gain=await readAudio();check(closeTo(gain.volume,.27,.015),effect.id+': gain control failed');}
    await page.evaluate(()=>{void window.previewAPI.restart();window.previewAPI.pause();});await wait(45);const race=await readAudio();check(race.paused,effect.id+': pending play promise restarted audio after immediate pause');report.previews.push({id:effect.id,pass:report.failures.length===failuresBefore,initial,played,paused:stable,sought,backwards,restarted,immediatePause:race,errors});
   }catch(e){check(false,effect.id+': '+e.message);report.previews.push({id:effect.id,pass:false,error:e.message});}finally{page.off('pageerror',listener);}for(const e of errors)check(false,effect.id+': '+e);
  }
  // Runtime mounting must not multiply audio tracks or lose per-instance variables.
  for(const fixture of args.has('--example-only')?[]:['audio-instances','audio-disabled']){
   const before=report.failures.length;try{await page.goto(base+'/'+fixture+'.html');await page.waitForFunction(()=>window.__playerReady&&document.querySelectorAll('audio').length===2&&[...document.querySelectorAll('audio')].every(a=>a.readyState>=2),{timeout:20000});
    const state=await page.evaluate(()=>({audios:[...document.querySelectorAll('audio')].map(a=>({id:a.id,src:a.currentSrc||a.src,muted:a.muted,volume:a.volume,declaredVolume:a.getAttribute('data-volume'),start:a.dataset.start,mediaStart:a.dataset.mediaStart,renderId:a.dataset.hfRenderId,host:a.closest('[data-composition-src]')?.id})),timelines:Object.keys(window.__timelines)}));
    check(new Set(state.audios.map(a=>a.id)).size===2,fixture+': audio ids not instance-unique');
    if(fixture==='audio-instances'){check(state.audios.some(a=>a.src.endsWith('/'+typeEffect.id+'.wav'))&&state.audios.some(a=>a.src.endsWith('/fade-in.wav')),'Different instances resolved same sound track');check(state.audios.some(a=>closeTo(a.volume,.31,.01))&&state.audios.some(a=>closeTo(a.volume,.63,.01)),'Per-instance gains lost');await page.evaluate(async()=>{window.__player.seek(3);await window.__hfWaitForSeekCompletion?.();});const positions=await page.evaluate(()=>[...document.querySelectorAll('audio')].map(a=>({src:a.src,time:a.currentTime,paused:a.paused})));check(positions.some(a=>a.src.endsWith('/'+typeEffect.id+'.wav')&&closeTo(a.time,1,.18)),'HyperFrames audio did not inherit parent start=2 at playhead=3');state.positions=positions;}else check(state.audios.every(a=>a.src.endsWith('/none.wav'))&&silence.nonzero===0,'Disabled or zero-gain template must select the verified all-zero PCM silence source');
    // Apply the installed compiler's render-id stamper to an authored duplicate-id
    // clone, then preserve those identifiers on the live runtime-mutated elements.
    const prior=await page.evaluate(({source,component})=>{const original=[...document.querySelectorAll('audio')],clone=document.implementation.createHTMLDocument('authored audio');for(const a of original){const c=a.cloneNode(false);c.id=component+'-sfx';c.removeAttribute('data-hf-render-id');c.setAttribute('src','assets/sfx/tracks/none.wav');clone.body.append(c);}const assign=new Function('document','var __getOwnPropNames=Object.getOwnPropertyNames;var __esm=(fn,res)=>function(){return fn&&(res=(0,fn[__getOwnPropNames(fn)[0]])(fn=0)),res;};'+source+';init_mediaRenderIds();assignMediaRenderIds(document);');assign(clone);return [...clone.querySelectorAll('audio')].map((a,i)=>{original[i].setAttribute('data-hf-render-id',a.dataset.hfRenderId);const parent=original[i].closest('[data-composition-src]'),start=Number(parent?.dataset.start||0);return{id:a.dataset.hfRenderId,src:'assets/sfx/tracks/none.wav',start,end:start+8,mediaStart:0,volume:.65,type:'audio'};});},{source:renderIdsSource,component:typeEffect.component});
    const reconciled=await engineContext.reconcile(page,{duration:12,videos:[],images:[],audios:structuredClone(prior)},base+'/');
    if(fixture==='audio-instances'){check(reconciled.composition.audios.length===2,'Engine probe duplicated or lost an audio track after runtime id change');check(reconciled.composition.audios.some(a=>a.src.endsWith('/typewriter.wav')&&a.start===2&&closeTo(a.volume,.31,.001))&&reconciled.composition.audios.some(a=>a.src.endsWith('/fade-in.wav')&&a.start===4&&closeTo(a.volume,.63,.001)),'Engine probe failed source/gain/parent-start reconciliation');}else check(reconciled.composition.audios.length===2&&reconciled.composition.audios.every(a=>a.src.endsWith('/none.wav'))&&silence.nonzero===0,'Engine probe did not preserve actual PCM silence for disabled or zero-gain tracks');
    state.engineProbe={scope:'Exact installed discovery/reconciliation functions; modeled compiled prior list, no mix or video encoding',prior,audios:reconciled.composition.audios,browserMedia:reconciled.browserMedia};
    report.templates.push({fixture,pass:report.failures.length===before,...state});
   }catch(e){check(false,fixture+': '+e.message);report.templates.push({fixture,pass:false,error:e.message});}
  }
  // Load the shipped example unchanged: this catches managed-media StaticGuard
  // failures that isolated gallery previews and a modeled probe cannot reveal.
  {const before=report.failures.length,errors=[],listener=e=>errors.push(e.message);page.on('pageerror',listener);try{
    await page.goto(base+'/examples/with-sound.html');await page.waitForFunction(()=>window.__playerReady&&window.__player&&document.querySelector('audio')?.readyState>=2,{timeout:20000});
    const ready=await page.evaluate(()=>({ready:window.__playerReady,effect:document.querySelector('[data-effect-id]')?.dataset.effectId,src:document.querySelector('audio').src,paused:document.querySelector('audio').paused}));check(ready.src.endsWith('/click-ripple.wav'),'Shipped example selected wrong sound track');
    await page.evaluate(async()=>{window.__player.seek(0);await window.__player.play();});await page.waitForFunction(()=>{const a=document.querySelector('audio');return a&&!a.paused&&a.currentTime>.08;},{timeout:4000});const playing=await readAudio();await page.evaluate(()=>window.__player.pause());const paused=await readAudio();await wait(70);const stable=await readAudio();check(paused.paused&&stable.paused&&Math.abs(stable.time-paused.time)<.03,'Shipped HyperFrames example does not stop sound on pause');await page.evaluate(async()=>{window.__player.seek(1.8);await window.__hfWaitForSeekCompletion?.();});const sought=await readAudio();check(closeTo(sought.time,1.8,.18)&&sought.paused,'Shipped HyperFrames example sound does not follow framework seek');for(const error of errors)check(false,'Shipped example: '+error);report.templates.push({fixture:'shipped-with-sound-example',pass:report.failures.length===before,ready,playing,paused:stable,sought,errors});
   }catch(e){check(false,'Shipped HyperFrames example: '+e.message);report.templates.push({fixture:'shipped-with-sound-example',pass:false,error:e.message,errors});}finally{page.off('pageerror',listener);}}
  // Verify exported templates contain real authored audio, with detectable sync source mutation.
  for(const component of manifest.components){const text=await fs.readFile(path.join(root,component.composition),'utf8');const state=await page.evaluate(html=>{const d=new DOMParser().parseFromString(html,'text/html'),t=d.querySelector('template'),node=(t?.content||d).querySelector('audio');return node?{id:node.id,src:node.getAttribute('src'),start:node.getAttribute('data-start'),duration:node.getAttribute('data-duration'),crossorigin:node.hasAttribute('crossorigin')}:null;},text);check(state&&state.id&&state.src&&Number(state.duration)>0&&!state.crossorigin,component.id+': no valid static export audio');const inline=[...text.matchAll(/<script(?![^>]*\bsrc\s*=)[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).join('\n');check(!/\bsfx\.muted\s*=/.test(inline),component.id+': managed audio uses forbidden imperative mute assignment');const mutations=detectSourceMutations?detectSourceMutations(inline):[];check(mutations.some(m=>m.selector==='#'+state?.id),component.id+': actual compiler AST detector missed static audio source change');}
  if(!args.has('--example-only'))try{
   await page.evaluateOnNewDocument(()=>{const NativeAudio=window.Audio;window.__audioTestObjects=[];window.Audio=function(...args){const a=new NativeAudio(...args);window.__audioTestObjects.push(a);return a;};window.Audio.prototype=NativeAudio.prototype;});
   await page.goto(base+'/catalog.html');await page.waitForSelector('.catalog-card');await page.click('[data-tab="sounds"]');check(await page.$$eval('.sound-card',a=>a.length)===sounds.length,'Sound bank does not list every sound');
   const longest=sounds.reduce((a,b)=>Number(a.duration)>Number(b.duration)?a:b);await page.click(`.sound-card[data-item-id="${longest.id}"]`);await page.waitForFunction(()=>window.__audioTestObjects.some(a=>!a.paused&&a.currentTime>0),{timeout:3000});const samplePlaying=await page.evaluate(()=>window.__audioTestObjects.filter(a=>!a.paused).length);check(samplePlaying===1,'Sound bank has overlapping sample players');await page.click('[data-tab="effects"]');const tabStopsSample=await page.evaluate(()=>window.__audioTestObjects.every(a=>a.paused));check(tabStopsSample,'Switching tabs left sound bank audio active');
   await page.click('.catalog-card');await page.waitForFunction(()=>document.getElementById('frame').contentWindow.__componentReady===true);await page.click('#play');await wait(120);const running=await page.evaluate(()=>[...document.getElementById('frame').contentDocument.querySelectorAll('audio')].map(a=>({paused:a.paused,time:a.currentTime})));check(running.length===1&&!running[0].paused&&running[0].time<.5,'Gallery first play should start audio from beginning');
   await page.$eval('#sound-gain',e=>{e.value='23';e.dispatchEvent(new Event('input',{bubbles:true}));});check(await page.evaluate(()=>Math.abs(document.getElementById('frame').contentDocument.querySelector('audio').volume-.23)<.01),'Gallery sound gain slider not connected');await page.click('#sound-enabled');check(await page.evaluate(()=>document.getElementById('frame').contentDocument.querySelector('audio').muted),'Gallery sound checkbox not connected');
   const editedProps=await page.$eval('#props',e=>JSON.parse(e.value));
   await page.evaluate(()=>{const original=URL.createObjectURL;URL.createObjectURL=blob=>{window.__exportTestBlob=blob;return original(blob);};document.addEventListener('click',e=>{if(e.target instanceof HTMLAnchorElement&&e.target.download)e.preventDefault();},true);});await page.click('#download-scene');const exported=await page.evaluate(async()=>JSON.parse(await window.__exportTestBlob.text()));check(exported.version===4&&exported.component&&exported.props&&exported.effect==='fade-in'&&exported.soundEnabled===false&&Math.abs(exported.soundGain-.23)<.001,'Scene JSON did not preserve effect/content/sound settings');
   check(Object.entries(editedProps).every(([k,v])=>JSON.stringify(exported.props[k])===JSON.stringify(v)),'Scene JSON changed edited content');
   await page.click('#sound-enabled');await page.click('#restart');await wait(70);await page.click('#close');await wait(70);const closed=await page.evaluate(()=>[...document.getElementById('frame').contentDocument.querySelectorAll('audio')].every(a=>a.paused));check(closed,'Gallery dialog close left audio active');report.gallery.push({sampleCount:sounds.length,samplePlaying,tabStopsSample,firstPlay:running,sceneExport:{component:exported.component,effect:exported.effect,soundEnabled:exported.soundEnabled,soundGain:exported.soundGain},closeStopsAudio:closed});
  }catch(e){check(false,'Gallery: '+e.message);}
  await page.close();
 }
}finally{if(browser){await browser.close();report.temporaryBrowserClosed=true;}if(server){await new Promise(resolve=>server.close(resolve));report.temporaryServerClosed=true;}}
if(priorReport){report.previousFullRunAt=priorReport.generatedAt;report.targetedRecheck='shipped-with-sound-example';report.previews=priorReport.previews;report.templates=[...priorReport.templates.filter(t=>t.fixture!=='shipped-with-sound-example'),...report.templates];report.gallery=priorReport.gallery;report.failures.push(...priorReport.failures.filter(f=>!f.startsWith('Shipped HyperFrames example:')&&!f.startsWith('Shipped example:')&&!f.startsWith('Missing served asset: /examples/')));}
report.serverErrors=serverErrors;for(const error of serverErrors)check(false,'Missing served asset: '+error.url);report.ok=report.failures.length===0;
if(args.has('--skip-previews'))report.scope='Targeted recheck: assets, templates, engine contracts and gallery; effect preview loop skipped, see prior full audio-verification.json.';
await fs.mkdir(path.join(root,'reports'),{recursive:true});await fs.writeFile(path.join(root,'reports',args.has('--skip-previews')?'audio-verification-targeted.json':'audio-verification.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({ok:report.ok,assets:report.assets.length,tracks:report.tracks.length,previews:report.previews.length,templates:report.templates.length,gallery:report.gallery,failures:report.failures},null,2));if(!report.ok)process.exitCode=1;
